services:

  api:
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-init:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile

    container_name: emotion-prediction-api

    ports:
      - "${API_PORT}:8000"

    volumes:
      - ./expirements:/app/expirements:ro
      - ./data:/app/data:ro
      - ./logs:/app/logs

    env_file:
      - .env

    environment:
      CONFIG_PATH: /app/config.ini
      CHECKPOINT_PATH: /app/expirements/dog_emotion_efficientnet_best.pth

    restart: unless-stopped

  cassandra:
    image: cassandra:5.0
    container_name: cassandra-dev
    ports: [ "${CASSANDRA_PORT}:9042" ]
    environment:
      CASSANDRA_CLUSTER_NAME: dev-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 256M
    volumes: [ cassandra-data:/var/lib/cassandra ]
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'describe cluster' >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      retries: 30
      start_period: 60s

  cassandra-init:
    image: cassandra:5.0
    container_name: cassandra-init
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./src/db/schema.cql:/schema.cql:ro
    command: cqlsh ${CASSANDRA_HOSTS} 9042 -f /schema.cql
    restart: on-failure

volumes:
  cassandra-data:
