name: CD

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  functional-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: |
          docker pull shpilevaanastasiya/big-data-lab2:latest

      - name: Install DVC (Google Drive support)
        run: |
          python3 -m venv .dvc-venv
          source .dvc-venv/bin/activate
          pip install --upgrade pip
          pip install "dvc[gdrive]" "pyOpenSSL==24.2.1"
          echo "$PWD/.dvc-venv/bin" >> "$GITHUB_PATH"

      - name: Configure DVC Google Drive OAuth client secret
        run: |
          dvc remote modify --local gdrive gdrive_client_secret "${{ secrets.GDRIVE_CLIENT_SECRET }}"

      - name: Pull trained checkpoint from DVC remote
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull expirements/dog_emotion_efficientnet_best.pth.dvc

      - name: Start container
        run: |
          docker run -d \
            --name emotion-api \
            -p 8000:8000 \
            -v "${{ github.workspace }}/expirements:/app/expirements:ro" \
            -e CHECKPOINT_PATH=/app/expirements/dog_emotion_efficientnet_best.pth \
            shpilevaanastasiya/big-data-lab2:latest

      - name: Wait for API
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8000/health; then
              exit 0
            fi
            sleep 2
          done

          echo "API did not start"
          docker logs emotion-api
          exit 1

      - name: Install test dependencies
        run: |
          pip install requests pytest

      - name: Run functional tests
        run: |
          pytest src/unit_tests/tests_functionality.py -v

      - name: Show container logs
        if: always()
        run: |
          docker logs emotion-api || true

      - name: Stop container
        if: always()
        run: |
          docker stop emotion-api || true
          docker rm emotion-api || true